### PR TITLE
Beef up example with actual robot code and simulation. Will help test out native builds

### PR DESCRIPTION
**Pull request by pjreiniger**
Basically rips off some of the wpilib examples. Using the new command framework. I would have sprinkled in rev / ctre / navx stuff, but they aren't supported on all native platforms this past year.

Also moves the example into a `cpp_example` subfolder, in the event we support java

### CODE REVIEW

**Comment by noamzaks** [comment]
Shouldn't we migrate the WPILib examples to Bazel?

**Comment by pjreiniger** [comment]
> Shouldn't we migrate the WPILib examples to Bazel?

In practice, the migration would be just adding a `WORKSPACE`, `BUILD` and `.bazelrc` file to all of their examples, so it seems a little silly to clone all of their examples to show the same 3 file pattern  60+ times, and then keep them in sync over time.

Furthermore, a lot of the examples are rather trivial and inconsistent. They are often hyper focused on illustrating a single concept rather than building a functioning robot. The fullest robot `GearsBot` doesn't include simulation. The examples that do have simulation are often single file `Robot.cpp`, which don't reflect how teams actually (at least I hope not) write their software. The same is true for rev and ctre examples.

**Comment by noamzaks** [comment]
I see

**Review by connorworley — APPROVED** [review]
lgtm, only suggestion would be to change subsystem pointers to references

**Pull request merged**
