### PR TITLE
Add navX support for Mac and Linux

### PR DESCRIPTION
**Pull request by akmin04**
Sort of an extension of #74.

navX doesn't host any pre-compiled library downloads for Mac or Linux, but the source code is downloadable and can be compiled.

Tested navx 4.0.425 + wpilib 2021 and navx 4.0.435 + wpilib 2022 on Mac

### CODE REVIEW

**Comment by akmin04** [comment]
Although I suppose this breaks the parallelism with gradleRio since navX on mac/linux becomes a bazelRio only feature. (I'm not sure why kauai labs doesn't offer mac/linux libraries in the first place)

**Comment by noamzaks** [comment]
I think we should adapt the python dependency-updating script to fetch the sources, so it stays up to date and doesn't break in the future

**Review by connorworley — APPROVED** [review]

**Comment by connorworley** [comment]
@akmin04 any interest in updating the script, or should we merge this in as-is?

**Comment by akmin04** [comment]
Sorry late reply - #94 looks good!

**Comment by pjreiniger** [comment]
Download source has landed. Note: I made the build scripts a file group instead of a library so you need to refactor a little bit.

I'd be ok building navx from source on all platforms instead of just Mac for consistency as well

**Comment by noamzaks** [comment]
This was superseded by #94 and #97 I believe

**Comment by pjreiniger** [comment]
OBE by #97. Thank you for the idea and the great start though.

**Pull request closed without merging**
