### PR TITLE
Add LD_LIBRARY_PATH to robotCommand, deploy progress bars, and hash checks

### PR DESCRIPTION
**Pull request by connorworley**
This makes robotCommand work and gives the user some feedback about their deploys. Hashing does improve performance by 2-3 seconds on my machine, with md5 being the fastest algorithm that's easy to get on a rio. We could probably go faster with some rolling crc or alder32 thing, but we would have to install a tool on the rio side to perform it.

first run (empty third-party/):
```
[23:26:29] ~/Code/bazelRio/bazelRio/examples/cpp_example time bazel run :robot.deploy --experimental_use_sandboxfs --platforms=@bazelrio//platforms/roborio
...

________________________________________________________
Executed in    7.99 secs   fish           external
   usr time  1201.71 millis  112.00 micros  1201.60 millis
   sys time  360.84 millis  782.00 micros  360.06 millis
```

second run:
```
[23:26:56] ~/Code/bazelRio/bazelRio/examples/cpp_example time bazel run :robot.deploy --experimental_use_sandboxfs --platforms=@bazelrio//platforms/roborio
...

________________________________________________________
Executed in    5.21 secs   fish           external
   usr time  435.89 millis  123.00 micros  435.76 millis
   sys time  225.19 millis  669.00 micros  224.52 millis
```

progress bars:

https://user-images.githubusercontent.com/1512426/141945547-689ae7fa-6335-4790-9787-8bcf4415bff9.mov

### CODE REVIEW

**Comment by noamzaks** [comment]
Neat. Md5 seems like the best option. I'll check later on my team's RIO

**Comment by connorworley** [comment]
it turns out my LD_LIBRARY_PATH approach didn't work and we need to use a path already configured in `/etc/ld.so.conf.d/frc_libs.conf`: `/usr/local/frc/third-party/lib`

**Review by noamzaks — APPROVED** [review]

**Comment by connorworley** [comment]
i'm going to clean this up a bit more before merging

**Comment by connorworley** [comment]
here's what the progress bar now looks like
https://user-images.githubusercontent.com/1512426/142066999-9b16bb08-a44b-4459-b8fc-8dfaf071a6e0.mov

**Pull request merged**
