### PR TITLE
Adding ability to build natively

### PR DESCRIPTION
**Pull request by pjreiniger**
Allows you to build for your local OS, and gives hooks to run with the simulation plugins. Tested on Windows and Linux (through docker)

`bazel run //:robot-sim-gui --config=windows`

### CODE REVIEW

**Comment by connorworley** [comment]
I run into the following on macOS:
```
[18:05:20] ~/Code/pjreiniger/bazelrio/examples/cpp_example bazel run //:robot-sim-gui --config=osx --experimental_use_sandboxfs
INFO: Analyzed target //:robot-sim-gui (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:robot-sim-gui up-to-date:
  bazel-bin/robot-sim-gui
INFO: Elapsed time: 0.167s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
dyld: Library not loaded: libwpilibNewCommands.dylib
  Referenced from: /private/var/tmp/_bazel_cbworley/816602bdc0486d9fa758522888be36ea/execroot/__main__/bazel-out/darwin-fastbuild/bin/robot-sim-gui
  Reason: image not found
fish: 'bazel run //:robot-sim-gui --co…' terminated by signal SIGABRT (Abort)
```

Not sure why. Here's what otool outputs...

```
[18:05:40] ~/Code/pjreiniger/bazelrio/examples/cpp_example otool -l /private/var/tmp/_bazel_cbworley/816602bdc0486d9fa758522888be36ea/execroot/__main__/bazel-out/darwin-fastbuild/bin/robot-sim-gui
/private/var/tmp/_bazel_cbworley/816602bdc0486d9fa758522888be36ea/execroot/__main__/bazel-out/darwin-fastbuild/bin/robot-sim-gui:
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __PAGEZERO
   vmaddr 0x0000000000000000
   vmsize 0x0000000100000000
  fileoff 0
 filesize 0
  maxprot 0x00000000
 initprot 0x00000000
   nsects 0
    flags 0x0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 632
  segname __TEXT
   vmaddr 0x0000000100000000
   vmsize 0x0000000000028000
  fileoff 0
 filesize 163840
  maxprot 0x00000005
 initprot 0x00000005
   nsects 7
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x0000000100006650
      size 0x000000000001dfb6
    offset 26192
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __stubs
   segname __TEXT
      addr 0x0000000100024606
      size 0x0000000000000bdc
    offset 148998
     align 2^1 (2)
    reloff 0
    nreloc 0
     flags 0x80000408
 reserved1 0 (index into indirect symbol table)
 reserved2 6 (size of stubs)
Section
  sectname __stub_helper
   segname __TEXT
      addr 0x00000001000251e4
      size 0x0000000000000512
    offset 152036
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __TEXT
      addr 0x0000000100025700
      size 0x00000000000007a8
    offset 153344
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __gcc_except_tab
   segname __TEXT
      addr 0x0000000100025ea8
      size 0x0000000000000b30
    offset 155304
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __cstring
   segname __TEXT
      addr 0x00000001000269d8
      size 0x0000000000000d19
    offset 158168
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __unwind_info
   segname __TEXT
      addr 0x00000001000276f4
      size 0x0000000000000900
    offset 161524
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 232
  segname __DATA_CONST
   vmaddr 0x0000000100028000
   vmsize 0x0000000000004000
  fileoff 163840
 filesize 16384
  maxprot 0x00000003
 initprot 0x00000003
   nsects 2
    flags 0x10
Section
  sectname __got
   segname __DATA_CONST
      addr 0x0000000100028000
      size 0x0000000000000170
    offset 163840
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 506 (index into indirect symbol table)
 reserved2 0
Section
  sectname __const
   segname __DATA_CONST
      addr 0x0000000100028170
      size 0x0000000000000cc0
    offset 164208
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 3
      cmd LC_SEGMENT_64
  cmdsize 232
  segname __DATA
   vmaddr 0x000000010002c000
   vmsize 0x0000000000004000
  fileoff 180224
 filesize 16384
  maxprot 0x00000003
 initprot 0x00000003
   nsects 2
    flags 0x0
Section
  sectname __la_symbol_ptr
   segname __DATA
      addr 0x000000010002c000
      size 0x0000000000000fd0
    offset 180224
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000007
 reserved1 552 (index into indirect symbol table)
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x000000010002cfd0
      size 0x00000000000013b8
    offset 184272
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 4
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x0000000100030000
   vmsize 0x0000000000060000
  fileoff 196608
 filesize 389064
  maxprot 0x00000001
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 5
            cmd LC_DYLD_INFO_ONLY
        cmdsize 48
     rebase_off 196608
    rebase_size 192
       bind_off 196800
      bind_size 3296
  weak_bind_off 200096
 weak_bind_size 52376
  lazy_bind_off 252472
 lazy_bind_size 7664
     export_off 260136
    export_size 32360
Load command 6
     cmd LC_SYMTAB
 cmdsize 24
  symoff 294584
   nsyms 2474
  stroff 338400
 strsize 247272
Load command 7
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 1800
     iextdefsym 1800
     nextdefsym 484
      iundefsym 2284
      nundefsym 190
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 334168
  nindirectsyms 1058
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 8
          cmd LC_LOAD_DYLINKER
      cmdsize 32
         name /usr/lib/dyld (offset 12)
Load command 9
     cmd LC_UUID
 cmdsize 24
    uuid 52C44019-5FB2-32D2-8423-5B96B31EFF6F
Load command 10
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 1
    minos 11.0
      sdk 11.1
   ntools 1
     tool 3
  version 609.8
Load command 11
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 12
       cmd LC_MAIN
   cmdsize 24
  entryoff 28464
 stacksize 0
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name libwpilibNewCommands.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 40
         name libwpiHal.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 15
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name libwpiHaljni.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 16
          cmd LC_LOAD_DYLIB
      cmdsize 40
         name libntcore.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 17
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name libntcorejni.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 18
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name libwpimath.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 19
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name libwpimathjni.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 20
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name libwpiutil.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 21
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name libwpiutiljni.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 22
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name libwpilibc.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 23
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name libhalsim_gui.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 24
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 1292.60.1
compatibility version 1.0.0
Load command 25
          cmd LC_RPATH
      cmdsize 144
         path @loader_path/_solib_darwin/_U@_U_Ubazelrio_Uedu_Uwpi_Ufirst_Uwpilibnewcommands_Uosxx86-64_S_S_Cshared_Ulibs___Uosx_Sx86-64_Sshared (offset 12)
Load command 26
          cmd LC_RPATH
      cmdsize 136
         path @loader_path/_solib_darwin/_U@_U_Ubazelrio_Uedu_Uwpi_Ufirst_Uhal_Uosxx86-64_S_S_Cshared_Ulibs___Uosx_Sx86-64_Sshared (offset 12)
Load command 27
          cmd LC_RPATH
      cmdsize 136
         path @loader_path/_solib_darwin/_U@_U_Ubazelrio_Uedu_Uwpi_Ufirst_Untcore_Uosxx86-64_S_S_Cshared_Ulibs___Uosx_Sx86-64_Sshared (offset 12)
Load command 28
          cmd LC_RPATH
      cmdsize 136
         path @loader_path/_solib_darwin/_U@_U_Ubazelrio_Uedu_Uwpi_Ufirst_Uwpimath_Uosxx86-64_S_S_Cshared_Ulibs___Uosx_Sx86-64_Sshared (offset 12)
Load command 29
          cmd LC_RPATH
      cmdsize 136
         path @loader_path/_solib_darwin/_U@_U_Ubazelrio_Uedu_Uwpi_Ufirst_Uwpiutil_Uosxx86-64_S_S_Cshared_Ulibs___Uosx_Sx86-64_Sshared (offset 12)
Load command 30
          cmd LC_RPATH
      cmdsize 136
         path @loader_path/_solib_darwin/_U@_U_Ubazelrio_Uedu_Uwpi_Ufirst_Uwpilibc_Uosxx86-64_S_S_Cshared_Ulibs___Uosx_Sx86-64_Sshared (offset 12)
Load command 31
          cmd LC_RPATH
      cmdsize 152
         path @loader_path/_solib_darwin/_U@_U_Ubazelrio_Uedu_Uwpi_Ufirst_Uhalsim_Uhalsim_Ugui_Uosxx86-64_S_S_Cshared_Ulibs___Uosx_Sx86-64_Sshared (offset 12)
Load command 32
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 292496
 datasize 2088
Load command 33
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 294584
 datasize 0
```

The dylibs referenced as rpaths exist, so I'm not sure why they aren't loading.
```
[18:06:48] ~/Code/pjreiniger/bazelrio/examples/cpp_example ls /private/var/tmp/_bazel_cbworley/816602bdc0486d9fa758522888be36ea/execroot/__main__/bazel-out/darwin-fastbuild/bin//_solib_darwin/_U@_U_Ubazelrio_Uedu_Uwpi_Ufirst_Uwpilibnewcommands_Uosxx86-64_S_S_Cshared_Ulibs___Uosx_Sx86-64_Sshared
libwpilibNewCommands.dylib
```

Maybe the ordering of load commands is wrong? I'm not really sure.

**Comment by connorworley** [comment]
dyld seems to not even try to handle the rpaths, so something strange is afoot
```
[18:34:49] ~/Code/pjreiniger/bazelrio/examples/cpp_example env DYLD_PRINT_RPATHS=1 /private/var/tmp/_bazel_cbworley/816602bdc0486d9fa758522888be36ea/execroot/__main__/bazel-out/darwin-fastbuild/bin/robot-sim-gui
dyld: Library not loaded: libwpilibNewCommands.dylib
  Referenced from: /private/var/tmp/_bazel_cbworley/816602bdc0486d9fa758522888be36ea/execroot/__main__/bazel-out/darwin-fastbuild/bin/robot-sim-gui
  Reason: image not found
fish: 'env DYLD_PRINT_RPATHS=1 /privat…' terminated by signal SIGABRT (Abort)
```

**Comment by pjreiniger** [comment]
Nice to finally have a mac tester with this stuff.

I reckon that the problem is because there are transitive shared library deps. The libraries must be in the LD_LIBRARY_PATH (or just the PATH on windows). I don't fully understand the witchcraft bazel does with its symlinks to get it to work, but it seems to on linux. On windows, symlinks are (practically) impossible, so it actually physically copies the .dll from the `bazel-out/external` path to where the binary lives. It seems like OSX isn't doing it correctly.

One option that I did with my version, which feels gross, would be to manually symlink them to the run directory. Java will need to do something like this anyway (I think. This is one of the super weird things I tried to figure out earlier, because allwpilib has super weird and unique requirements)


Now, having said all that, should we fix it in this, or do a follow up PR?

**Comment by noamzaks** [comment]
I think we should do a follow up PR so we can continue creating PRs now (This is quite a substantial amount of changes)

**Review by noamzaks — APPROVED** [review]
lgtm

**Comment by connorworley** [comment]
I agree that we should go ahead and land this. I don't know if transitive deps are the issue, because dyld doesn't doesn't seem to be loading any of the first-order dependencies, but I'm curious as to what you were seeing on linux for comparison.

**Pull request merged**
