### PR TITLE
Add Kotlin support

### PR DESCRIPTION
**Pull request by connorworley**
Most of this is just porting the Java example to Kotlin. I didn't need to change `robot_java_binary` because `java_binary` can take `kt_jvm_library` as a dep just fine and the transitive dep stuff works. I've renamed `robot_java_binary` to `robot_jvm_binary` to avoid confusion.

### CODE REVIEW

**Review by noamzaks — APPROVED** [review]
lgtm, tested on macOS

**Review by pjreiniger — APPROVED** [review]
I'm not familiar enough with kotlin to review the example, but the other stuff looks good. It certainly isn't standard java, so if you got it to deploy and it builds CI that is good enough for me.

You should add the example to the CI script though.

**Comment by connorworley** [comment]
Added build tests. I also decided to change `robot_jvm_binary` back to `robot_java_binary` since the fact that we make a `java_binary` internally is pretty leaky. I think it's probably better to make that obvious and document how kotlin is supported through `runtime_deps`.

**Comment by connorworley** [comment]
Okay, I've done some debugging and determined that `--enable_runfiles` breaks Kotlin builds on Windows, but disabling it breaks our deloy script. I'm going to land this and temporarily break the deploy script, and come up with a fix for it shortly.

**Pull request merged**
